### ISSUE TITLE
Consider handling text that has long sequences of digits

### ISSUE THREAD

**Issue by lread** [wevre/natural-compare#4]
## Currently

Digit sequences are parsed using `Long/parseLong` in clj and `js/parseInt` in cljs.

This means that digit sequences that exceed max long will cause failures.

## Repro

```Clojure
$ clj -Sdeps '{:deps {wevre/natural-compare {:mvn/version "0.0.8"}}}'  
Clojure 1.11.3
user=> (require '[wevre.natural-compare :refer [natural-compare]])
nil
user=> (def ss ["t3" "t1" "t11111111111111111111" "t10" "t12" "t2" "t27"])
#'user/ss
user=> (sort natural-compare ss)
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).
For input string: "11111111111111111111"
```

## Options

Some options for consideration

1. Do nothing. It's not a use case you care to cover. 
2. Document limitation in README.
3. Parse numbers into BigInteger (clj) and BigInt (cljs)
4. Write a custom compare for integer strings

It seems to me that option 3 would be the easiest if you want to address this.
I expect though, that it might have a performance impact? Is that important for this lib?
If so option 4 might be worth weighing against option 3 for performance.

## Next Steps
Happy to help with a PR if you want to address this.

**Comment by wevre** [comment]
Maybe an alternate version `natural-compare'` that supports arbitrary precision.

But I'm leaning more towards 1 or 2.

It still feels to me like this is such a small function that folks don't need it be a library, they can just copy it directly into their own project.

**Comment by lread** [comment]
Yah, that's totally reasonable. Feel free to close this issue if you opt for 1! :slightly_smiling_face:

**Comment by wevre** [comment]
I'll update the read me alerting about the limitation.
